### ISSUE TITLE
MediaObjectsForURL requires ability to differentiate binary and ASCII sources

### ISSUE THREAD

**Issue by chrisfu** [chrisfu/TuneIn.bundle#2]
Echoing the information given in [this](http://forums.plex.tv/discussion/175768/reviving-development-of-the-tunein-bundle-channel-progress-already-made) forum post.

At the moment, MediaObjectsForURL expects to hit a binary stream but will occasionally be handed a text file in the form of an m3u/pls playlist. The BBC/Absolute (UK) radio stations are a prime example of this behaviour.

Rather than try and pass non binary data directly to PlayTrack, it needs to further parse this formatted playlist and select another steam in a suitable bitrate/format, before passing that result (if binary) to PlayTrack.

As far as I can see that should mean that a majority/all steams will work perfectly within the channel.

**Comment by solvek** [comment]
Now I am getting direct stream url and can play them. So this issue may be out of date.

However there can be the question which bitrate to use if we have multiple of them. My implementation just chooses the most reliable stream (basing on "reliability" attribute).

**Comment by chrisfu** [comment]
@solvek That's a more than reasonable approach for now. In future I guess that it'd be prudent to allow the user to pick their favored setting,

To be honest though, it's more critical for mobile users and I'd imagine that most will be using this on smart TV's, Chromecasts, ATV's and the like. Bitrate isn't much of an issue to those folk.

In other news, I've just tested your work and everything works great for me. I'll open a new pull request and hopefully get our (but mostly your!) work pushed upstream.
